version: 2.1

orbs:
  docker: circleci/docker@1.5.0

commands:
  install-packages:
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "schema.prisma" }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-dependencies-{{ checksum "schema.prisma" }}-{{ checksum "package.json" }}-
            - v2-dependencies-{{ checksum "schema.prisma" }}-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: |
            v2-dependencies-{{ checksum "schema.prisma" }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

jobs:
  build:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - install-packages
      - run: npm run build
      - store_artifacts:
          path: ./dist

  lint-prettier:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - install-packages
      - run: npm run lint:prettier

  lint-eslint:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - install-packages
      - run: npm run lint:eslint -- --format junit --output-file ./junit/eslint.xml
      - store_test_results:
          path: ./junit

  ts-check:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - install-packages
      - run: npm run ts-check

workflows:
  version: 2
  develop:
    jobs:
      - lint-eslint
      - lint-prettier
      - docker/hadolint:
          dockerfiles: Dockerfile
      - ts-check
      - build:
          requires:
            - lint-eslint
            - lint-prettier
            - ts-check
      - docker/publish:
          context:
            - ghcr
          requires:
            - docker/hadolint
            - build
          filters:
            branches:
              only: develop
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: ghcr.io
          tag: develop
      - docker/publish:
          context:
            - ghcr
          requires:
            - docker/hadolint
            - build
          filters:
            branches:
              ignore:
                - develop
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: ghcr.io
